sonar.projectKey=tinchoram_UPE-TESTING-2026
sonar.projectName=UPE-TESTING-2026
sonar.organization=tinchoram
sonar.projectVersion=1.0
sonar.sources=demo-sonar
sonar.sourceEncoding=UTF-8

# recomendado hoy para C-family
sonar.cfamily.compile-commands=bw-output/compile_commands.json